source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit', '~> 0.15.0'
pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON'
pod 'Kingfisher', '~> 1.6.0'
pod 'YYModel'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']

